export const cityOptions = {
  Drenthe: ['Assen', 'Coevorden', 'Emmen', 'Hoogeveen', 'Meppel'],
  Flevoland: ['Almere', 'Biddinghuizen', 'Emmeloord', 'Lelystad'],
  Friesland: [
    'Bolsward',
    'Dokkum',
    'Franeker',
    'Harlingen',
    'Hindeloopen',
    'IJlst',
    'Leeuwarden',
    'Sloten',
    'Sneek',
    'Stavoren',
    'Workum',
  ],
  Gelderland: ['Apeldoorn', 'Arnhem', 'Bredevoort', 'Buren', 'Borculo', 'Bronkhorst', 'Culemborg', 'Dieren'],
  Groningen: ['Groningen', 'Appingedam', 'Delfzijl', 'Hoogezand', 'Stadskanaal', 'Winschoten'],
  Limburg: ['Maastricht', 'Roermond', 'Venlo', 'Weert', 'Sittard', 'Heerlen'],
  'Noord-Brabant': ['Eindhoven', 'Tilburg', 'Breda', "'s-Hertogenbosch", 'Helmond'],
  'Noord-Holland': ['Amsterdam', 'Haarlem', 'Alkmaar', 'Hoorn', 'Enkhuizen', 'Zaanstad'],
  Overijssel: ['Zwolle', 'Deventer', 'Enschede', 'Almelo', 'Hengelo'],
  Utrecht: ['Utrecht', 'Amersfoort', 'Nieuwegein', 'Veenendaal'],
  Zeeland: ['Middelburg', 'Vlissingen', 'Goes', 'Terneuzen'],
  'Zuid-Holland': ['Rotterdam', 'The Hague', 'Leiden', 'Dordrecht', 'Delft', 'Gouda'],
}
