export const cityOptions = {
  Drenthe: [
    'Assen',
    'Coevorden',
    'Emmen',
    'Hoogeveen',
    'Meppel',
    'Beilen',
    'Borger',
    'Roden',
    'Gieten',
    'Eelde',
    'Zuidlaren',
    'Nieuw-Amsterdam',
    'Vries',
    'Diever',
    'Dwingeloo',
  ],
  Flevoland: [
    'Almere',
    'Biddinghuizen',
    'Emmeloord',
    'Lelystad',
    'Dronten',
    'Zeewolde',
    'Urk',
    'Swifterbant',
    'Rutten',
  ],
  Friesland: [
    'Leeuwarden',
    'Sneek',
    'Heerenveen',
    'Drachten',
    'Franeker',
    'Harlingen',
    'Bolsward',
    'Dokkum',
    'Sloten',
    'Stavoren',
    'Workum',
    'IJlst',
    'Hindeloopen',
    'Gorredijk',
    'Joure',
    'Wolvega',
    'Buitenpost',
    'Oosterwolde',
  ],
  Gelderland: [
    'Apeldoorn',
    'Arnhem',
    'Nijmegen',
    'Ede',
    'Harderwijk',
    'Tiel',
    'Winterswijk',
    'Culemborg',
    'Zutphen',
    'Doetinchem',
    'Barneveld',
    'Elburg',
    'Hattem',
    'Borculo',
    'Buren',
    'Dieren',
    'Epe',
    'Ermelo',
    'Nijkerk',
    'Putten',
    'Renkum',
    'Rheden',
    'Wageningen',
    'Zevenaar',
  ],
  Groningen: [
    'Groningen',
    'Appingedam',
    'Delfzijl',
    'Hoogezand',
    'Winschoten',
    'Stadskanaal',
    'Veendam',
    'Haren',
    'Leek',
    'Pekela',
    'Uithuizen',
    'Zuidhorn',
    'Loppersum',
    'Ten Boer',
    'Bedum',
  ],
  Limburg: [
    'Maastricht',
    'Roermond',
    'Venlo',
    'Weert',
    'Sittard',
    'Heerlen',
    'Kerkrade',
    'Geleen',
    'Valkenburg',
    'Echt',
    'Gennep',
    'Tegelen',
    'Horst',
    'Meerssen',
  ],
  'Noord-Brabant': [
    'Eindhoven',
    'Tilburg',
    'Breda',
    "'s-Hertogenbosch",
    'Helmond',
    'Oss',
    'Roosendaal',
    'Bergen op Zoom',
    'Waalwijk',
    'Uden',
    'Veghel',
    'Vught',
    'Oosterhout',
    'Etten-Leur',
    'Son en Breugel',
    'Boxtel',
  ],
  'Noord-Holland': [
    'Amsterdam',
    'Haarlem',
    'Alkmaar',
    'Hilversum',
    'Zaandam',
    'Hoorn',
    'Purmerend',
    'Den Helder',
    'Beverwijk',
    'Heerhugowaard',
    'Haarlemmermeer',
    'Enkhuizen',
    'Zaanstad',
    'Edam-Volendam',
    'Landsmeer',
    'Medemblik',
    'Uitgeest',
    'Velsen',
    'Weesp',
    'Wormerland',
    'Opmeer',
  ],
  Overijssel: [
    'Zwolle',
    'Deventer',
    'Enschede',
    'Almelo',
    'Hengelo',
    'Kampen',
    'Raalte',
    'Steenwijk',
    'Hardenberg',
    'Oldenzaal',
    'Borne',
    'Haaksbergen',
    'Losser',
    'Ommen',
    'Tubbergen',
    'Wierden',
    'Dalfsen',
  ],
  Utrecht: [
    'Utrecht',
    'Amersfoort',
    'Nieuwegein',
    'Veenendaal',
    'Zeist',
    'Houten',
    'De Bilt',
    'Woerden',
    'Soest',
    'IJsselstein',
    'Baarn',
    'Leusden',
    'Bunnik',
    'Rhenen',
  ],
  Zeeland: [
    'Middelburg',
    'Vlissingen',
    'Goes',
    'Terneuzen',
    'Zierikzee',
    'Hulst',
    'Tholen',
    'Borsele',
    'Sluis',
    'Veere',
  ],
  'Zuid-Holland': [
    'Rotterdam',
    'The Hague',
    'Leiden',
    'Dordrecht',
    'Delft',
    'Gouda',
    'Zoetermeer',
    'Schiedam',
    'Vlaardingen',
    'Spijkenisse',
    'Alphen aan den Rijn',
    'Capelle aan den IJssel',
    'Katwijk',
    'Gorinchem',
    'Hellevoetsluis',
    'Rijswijk',
    'Wassenaar',
    'Voorburg',
  ],
}
